In [2]:
import pandas as pd 
import numpy as np

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credits

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [6]:
movies = movies.merge(credits,on='title')

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
movies = movies[['movie_id','genres','keywords','overview','cast','crew','title']]

In [9]:
movies.dropna(inplace=True)

In [10]:
movies.isnull().sum()

movie_id    0
genres      0
keywords    0
overview    0
cast        0
crew        0
title       0
dtype: int64

In [11]:
movies.duplicated().sum()

0

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

## convertion function

In [13]:
import ast
def convert (obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [14]:
movies['genres']=movies['genres'].apply(convert)

In [15]:
movies.keywords[1]

'[{"id": 270, "name": "ocean"}, {"id": 726, "name": "drug abuse"}, {"id": 911, "name": "exotic island"}, {"id": 1319, "name": "east india trading company"}, {"id": 2038, "name": "love of one\'s life"}, {"id": 2052, "name": "traitor"}, {"id": 2580, "name": "shipwreck"}, {"id": 2660, "name": "strong woman"}, {"id": 3799, "name": "ship"}, {"id": 5740, "name": "alliance"}, {"id": 5941, "name": "calypso"}, {"id": 6155, "name": "afterlife"}, {"id": 6211, "name": "fighter"}, {"id": 12988, "name": "pirate"}, {"id": 157186, "name": "swashbuckler"}, {"id": 179430, "name": "aftercreditsstinger"}]'

In [16]:
movies['keywords'] = movies['keywords'].apply(convert)

In [17]:
movies.cast[0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [18]:
# we only nee first three name only 
def convert3 (obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter !=3:
            L.append(i['name'])
            counter+1
        else:
            break
    return L

In [19]:
movies['cast'] = movies['cast'].apply(convert3)

In [20]:
movies

,movie_id,genres,keywords,overview,cast,crew,title
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Avatar
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",Pirates of the Caribbean: At World's End
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",Spectre
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",The Dark Knight Rises
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",John Carter
...,...,...,...,...,...,...,...
4804,9367,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...",El Mariachi just wants to play his guitar and ...,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de...",El Mariachi
4805,72766,"[Comedy, Romance]",[],A newlywed couple's honeymoon is upended by th...,"[Edward Burns, Kerry Bishé, Marsha Dietlein, C...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de...",Newlyweds
4806,231617,"[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","""Signed, Sealed, Delivered"" introduces a dedic...","[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de...","Signed, Sealed, Delivered"
4807,126186,[],[],When ambitious New York attorney Sam is sent t...,"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de...",Shanghai Calling
4808,25975,[Documentary],"[obsession, camcorder, crush, dream girl]",Ever since the second grade when he first saw ...,"[Drew Barrymore, Brian Herzlinger, Corey Feldm...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de...",My Date with Drew

In [21]:
movies.crew[1]

'[{"credit_id": "52fe4232c3a36847f800b579", "department": "Camera", "gender": 2, "id": 120, "job": "Director of Photography", "name": "Dariusz Wolski"}, {"credit_id": "52fe4232c3a36847f800b4fd", "department": "Directing", "gender": 2, "id": 1704, "job": "Director", "name": "Gore Verbinski"}, {"credit_id": "52fe4232c3a36847f800b54f", "department": "Production", "gender": 2, "id": 770, "job": "Producer", "name": "Jerry Bruckheimer"}, {"credit_id": "52fe4232c3a36847f800b503", "department": "Writing", "gender": 2, "id": 1705, "job": "Screenplay", "name": "Ted Elliott"}, {"credit_id": "52fe4232c3a36847f800b509", "department": "Writing", "gender": 2, "id": 1706, "job": "Screenplay", "name": "Terry Rossio"}, {"credit_id": "52fe4232c3a36847f800b57f", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "52fe4232c3a36847f800b585", "department": "Editing", "gender": 2, "id": 1722, "job": "Editor", "name": "Craig Wood"}, {"credit_id": "52fe4232c3a36847f800b573", "department": "Sound", "gender": 2, "id": 947, "job": "Original Music Composer", "name": "Hans Zimmer"}, {"credit_id": "52fe4232c3a36847f800b555", "department": "Production", "gender": 2, "id": 2444, "job": "Executive Producer", "name": "Mike Stenson"}, {"credit_id": "52fe4232c3a36847f800b561", "department": "Production", "gender": 2, "id": 2445, "job": "Producer", "name": "Eric McLeod"}, {"credit_id": "52fe4232c3a36847f800b55b", "department": "Production", "gender": 2, "id": 2446, "job": "Producer", "name": "Chad Oman"}, {"credit_id": "52fe4232c3a36847f800b567", "department": "Production", "gender": 0, "id": 2447, "job": "Producer", "name": "Peter Kohn"}, {"credit_id": "52fe4232c3a36847f800b56d", "department": "Production", "gender": 0, "id": 2448, "job": "Producer", "name": "Pat Sandston"}, {"credit_id": "52fe4232c3a36847f800b58b", "department": "Production", "gender": 1, "id": 2215, "job": "Casting", "name": "Denise Chamian"}, {"credit_id": "52fe4232c3a36847f800b597", "department": "Art", "gender": 2, "id": 1226, "job": "Production Design", "name": "Rick Heinrichs"}, {"credit_id": "52fe4232c3a36847f800b59d", "department": "Art", "gender": 2, "id": 553, "job": "Art Direction", "name": "John Dexter"}, {"credit_id": "52fe4232c3a36847f800b591", "department": "Production", "gender": 1, "id": 3311, "job": "Casting", "name": "Priscilla John"}, {"credit_id": "52fe4232c3a36847f800b5a3", "department": "Art", "gender": 1, "id": 4032, "job": "Set Decoration", "name": "Cheryl Carasik"}, {"credit_id": "52fe4232c3a36847f800b5a9", "department": "Costume & Make-Up", "gender": 0, "id": 4033, "job": "Costume Design", "name": "Liz Dann"}, {"credit_id": "52fe4232c3a36847f800b5af", "department": "Costume & Make-Up", "gender": 1, "id": 4034, "job": "Costume Design", "name": "Penny Rose"}, {"credit_id": "56427ce8c3a3686a53000d8b", "department": "Sound", "gender": 2, "id": 5132, "job": "Music Supervisor", "name": "Bob Badami"}, {"credit_id": "55993c15c3a36855db002f33", "department": "Art", "gender": 2, "id": 146439, "job": "Conceptual Design", "name": "James Ward Byrkit"}, {"credit_id": "52fe4232c3a36847f800b5b9", "department": "Costume & Make-Up", "gender": 1, "id": 406204, "job": "Makeup Department Head", "name": "Ve Neill"}, {"credit_id": "56e47f7892514132690017bd", "department": "Crew", "gender": 2, "id": 1259516, "job": "Stunts", "name": "John Dixon"}, {"credit_id": "5740be639251416597000849", "department": "Crew", "gender": 0, "id": 1336716, "job": "CGI Supervisor", "name": "Dottie Starling"}, {"credit_id": "56427c639251412fc8000dc1", "department": "Directing", "gender": 1, "id": 1344278, "job": "Script Supervisor", "name": "Pamela Alch"}, {"credit_id": "57083101c3a3681d320004e6", "department": "Crew", "gender": 0, "id": 1368867, "job": "Special Effects Coordinator", "name": "Allen Hall"}, {"credit_id": "56427d5ec3a3686a62000d4a", "department": "Sound", "gender": 0, "id": 1368884, "job": "Music Editor", "name": "Melissa Muik"}, {"credit_id": "56427c7b9251412fd4000e07", "department": "Directing", "gender": 1, "id": 1395290, "job": "Script Supervisor", "name": "Sharron Reynolds"}, {"credit_id": "56427d2bc3a3686a53000d9b", "department": "Sound", "gender": 0, "id": 1399327, "job": "Music Editor", "name": "Barbara McDermott"}, {"credit_id": "56427cb4c3a3686a53000d87", "department": "Directing", "gender": 1, "id": 1400738, "job": "Script Supervisor", "name": "Karen Golden"}, {"credit_id": "56427d169251412fd4000e23", "department": "Sound", "gender": 0, "id": 1534197, "job": "Music Editor", "name": "Katie Greathouse"}]'

# fetching the director

In [22]:

def fetch_director (obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

In [23]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [24]:
movies.overview[1]

'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.'

# extracting the Overview column

In [25]:
movies['overview']=movies['overview'].apply(lambda x:x.split() )

In [26]:
movies

,movie_id,genres,keywords,overview,cast,crew,title
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],Avatar
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],Pirates of the Caribbean: At World's End
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes],Spectre
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],The Dark Knight Rises
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],John Carter
...,...,...,...,...,...,...,...
4804,9367,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, pap...","[El, Mariachi, just, wants, to, play, his, gui...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez],El Mariachi
4805,72766,"[Comedy, Romance]",[],"[A, newlywed, couple's, honeymoon, is, upended...","[Edward Burns, Kerry Bishé, Marsha Dietlein, C...",[Edward Burns],Newlyweds
4806,231617,"[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","[""Signed,, Sealed,, Delivered"", introduces, a,...","[Eric Mabius, Kristin Booth, Crystal Lowe, Geo...",[Scott Smith],"Signed, Sealed, Delivered"
4807,126186,[],[],"[When, ambitious, New, York, attorney, Sam, is...","[Daniel Henney, Eliza Coupe, Bill Paxton, Alan...",[Daniel Hsia],Shanghai Calling
4808,25975,[Documentary],"[obsession, camcorder, crush, dream girl]","[Ever, since, the, second, grade, when, he, fi...","[Drew Barrymore, Brian Herzlinger, Corey Feldm...",[Brian Herzlinger],My Date with Drew

# removing the space

In [27]:
movies['genres']=movies['genres'].apply(lambda x : [i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x : [i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x : [i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x : [i.replace(" ","") for i in x])

In [28]:
movies.head()

,movie_id,genres,keywords,overview,cast,crew,title
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],Avatar
1,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],Pirates of the Caribbean: At World's End
2,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],Spectre
3,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],The Dark Knight Rises
4,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],John Carter

In [29]:
movies['tags']=movies['genres']+movies['keywords']+movies['cast']+movies['overview']+movies['crew']

In [30]:
new_df = movies[['movie_id','title','tags']]

In [31]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."
...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller, unitedstates–mexicob..."
4805,72766,Newlyweds,"[Comedy, Romance, EdwardBurns, KerryBishé, Mar..."
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TVMovie, date, loveat..."
4807,126186,Shanghai Calling,"[DanielHenney, ElizaCoupe, BillPaxton, AlanRuc..."
4808,25975,My Date with Drew,"[Documentary, obsession, camcorder, crush, dre..."

In [32]:
new_df['tags']= new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\milan\AppData\Local\Temp\ipykernel_19636\335926201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(lambda x:" ".join(x))

In [33]:
new_df

,movie_id,title,tags
0,19995,Avatar,Action Adventure Fantasy ScienceFiction cultur...
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drugabuse exoti...
2,206647,Spectre,Action Adventure Crime spy basedonnovel secret...
3,49026,The Dark Knight Rises,Action Crime Drama Thriller dccomics crimefigh...
4,49529,John Carter,Action Adventure ScienceFiction basedonnovel m...
...,...,...,...
4804,9367,El Mariachi,Action Crime Thriller unitedstates–mexicobarri...
4805,72766,Newlyweds,Comedy Romance EdwardBurns KerryBishé MarshaDi...
4806,231617,"Signed, Sealed, Delivered",Comedy Drama Romance TVMovie date loveatfirsts...
4807,126186,Shanghai Calling,DanielHenney ElizaCoupe BillPaxton AlanRuck Zh...
4808,25975,My Date with Drew,Documentary obsession camcorder crush dreamgir...

In [34]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\milan\AppData\Local\Temp\ipykernel_19636\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

## **Applying Algorithem sklearn**

#### **steming --> ['loving','lover','love'] ---> ['love','love','love']**

In [35]:
import nltk

In [36]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [37]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [38]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\milan\AppData\Local\Temp\ipykernel_19636\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [40]:
vectors =cv.fit_transform(new_df['tags']).toarray()

In [41]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [42]:
len(cv.get_feature_names_out())

5000

## cosine algoirithem to find the distance between the Vectors

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

In [44]:
similarity = cosine_similarity(vectors)

In [45]:
similarity[1]

array([0.06818182, 1.        , 0.07644708, ..., 0.02153652, 0.        ,
       0.02383656])

In [46]:
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x:x[1])

[(0, 0.9999999999999998),
 (1216, 0.27028123880866767),
 (582, 0.23162743094465488),
 (2333, 0.22996655275195),
 (3730, 0.22498852128662872),
 (507, 0.22438727760202976),
 (539, 0.22305671869347438),
 (1920, 0.22010219462003333),
 (2409, 0.2175970699446223),
 (4048, 0.20751433915982237),
 (2786, 0.20695933859617893),
 (322, 0.20691022044226628),
 (577, 0.20100756305184242),
 (778, 0.19968076595771792),
 (1204, 0.19790977371009408),
 (61, 0.19596237883454903),
 (2971, 0.19462473604038075),
 (74, 0.19382872151427658),
 (151, 0.1928473039599675),
 (4192, 0.1928473039599675),
 (3608, 0.19145989526687088),
 (1089, 0.18540496217739155),
 (3999, 0.18463723646899916),
 (1444, 0.18281810603178267),
 (973, 0.18098069149825674),
 (260, 0.1809806914982567),
 (1194, 0.17837651700316892),
 (3327, 0.1776672636296754),
 (3675, 0.175919798853417),
 (1537, 0.17588161767036212),
 (495, 0.17407765595569785),
 (4405, 0.17407765595569785),
 (972, 0.17348855898381338),
 (4, 0.17056057308448835),
 (3538, 0.16898159235484367),
 (83, 0.1688801323682996),
 (2999, 0.16854996561581054),
 (27, 0.1682904582015223),
 (305, 0.1682904582015223),
 (184, 0.16685595311797868),
 (47, 0.16351748504193214),
 (942, 0.16262312563634837),
 (2204, 0.160930171455096),
 (172, 0.1599005372667078),
 (2075, 0.1599005372667078),
 (4336, 0.15909090909090912),
 (1275, 0.15745916432444343),
 (1329, 0.15745916432444343),
 (168, 0.15731330124142318),
 (3162, 0.15701373439577193),
 (595, 0.15559397856603546),
 (1071, 0.15392982399673985),
 (1321, 0.15386436372416595),
 (220, 0.15075567228888181),
 (661, 0.15075567228888181),
 (529, 0.1507556722888818),
 (36, 0.1492405014489273),
 (300, 0.1492405014489273),
 (931, 0.1487044791289829),
 (1201, 0.1487044791289829),
 (373, 0.14782809899727067),
 (2731, 0.14782809899727067),
 (41, 0.14777011582226215),
 (150, 0.14716573653773893),
 (1178, 0.14673479641335554),
 (1831, 0.1463423517512409),
 (4010, 0.14625448482542613),
 (139, 0.14519080172812554),
 (2515, 0.14506471329641488),
 (91, 0.14484136487558028),
 (1344, 0.14484136487558028),
 (342, 0.1446354779699756),
 (581, 0.14245072057454744),
 (1673, 0.1421338109037403),
 (1982, 0.14126448280440335),
 (158, 0.1411569346481171),
 (56, 0.1399731277389636),
 (1479, 0.13977653617040256),
 (3354, 0.13762047064079508),
 (838, 0.1374416265488099),
 (2760, 0.13623731522826651),
 (208, 0.13483997249264842),
 (1273, 0.13483997249264842),
 (1383, 0.13483997249264842),
 (1396, 0.13402192668680965),
 (127, 0.1340050420345616),
 (94, 0.13336626734231613),
 (187, 0.13336626734231613),
 (1938, 0.13336626734231613),
 (937, 0.1332504477222565),
 (1327, 0.1315903389919538),
 (1488, 0.1315903389919538),
 (2970, 0.1315903389919538),
 (557, 0.1305582419667734),
 (1355, 0.1305582419667734),
 (149, 0.13005121775247103),
 (461, 0.1292719224987548),
 (3409, 0.1292719224987548),
 (4538, 0.12921914767618442),
 (311, 0.1292191476761844),
 (1056, 0.1292191476761844),
 (1965, 0.12892415701965754),
 (3781, 0.128564869306645),
 (67, 0.12792042981336627),
 (513, 0.12792042981336627),
 (413, 0.12741179785940637),
 (568, 0.12741179785940637),
 (46, 0.1266600992762247),
 (157, 0.1257389226923863),
 (490, 0.1257389226923863),
 (1301, 0.1257389226923863),
 (1945, 0.1256297269074015),
 (108, 0.12543630150106364),
 (17, 0.12436708454077278),
 (502, 0.12424730498438732),
 (275, 0.12392039927415242),
 (859, 0.12392039927415242),
 (2169, 0.12392039927415242),
 (2496, 0.12392039927415242),
 (4079, 0.12392039927415242),
 (1322, 0.12351231781710245),
 (2584, 0.12309149097933275),
 (3982, 0.12309149097933275),
 (579, 0.12227899701112964),
 (294, 0.12227899701112963),
 (1808, 0.12227899701112963),
 (1297, 0.12196734422726127),
 (2133, 0.12196734422726127),
 (95, 0.12196734422726126),
 (777, 0.12087344460380703),
 (31, 0.1207011373963169),
 (1560, 0.1207011373963169),
 (2181, 0.1207011373963169),
 (668, 0.12060453783110546),
 (1373, 0.12060453783110546),
 (26, 0.11980845957463077),
 (843, 0.11918282365569904),
 (2686, 0.11918282365569904),
 (3628, 0.11918282365569904),
 (505, 0.11826247919781653),
 (2378, 0.11826247919781653),
 (111, 0.11776030079682895),
 (589, 0.11776030079682895),
 (2873, 0.11776030079682895),
 (3622, 0.11772040233700279),
 (206, 0.11725441178024137),
 (1299, 0.11631052629980887),
 (4230, 0.11631052629980887),
 (2652, 0.1160517706371319),
 (122, 0.11495012246792571),
 (1086, 0.11495012246792571),
 (1220, 0.11487593716012254),
 (466, 0.11396057645963795),
 (476, 0.11396057645963795),
 (773, 0.11396057645963795),
 (935, 0.11396057645963795),
 (7, 0.11306675421666137),
 (84, 0.11306675421666137),
 (102, 0.11306675421666137),
 (1741, 0.11306675421666137),
 (1878, 0.11306675421666137),
 (1715, 0.11306675421666136),
 (4348, 0.11306675421666136),
 (138, 0.11236664374387369),
 (1015, 0.11236664374387369),
 (2450, 0.11236664374387369),
 (3235, 0.11236664374387369),
 (487, 0.11197850219117086),
 (1774, 0.11197850219117086),
 (4673, 0.11197850219117086),
 (72, 0.11113855611859677),
 (1401, 0.11113855611859677),
 (2372, 0.11113855611859677),
 (1004, 0.11009637651263605),
 (1047, 0.11009637651263605),
 (1658, 0.11009637651263605),
 (549, 0.10994987428338562),
 (2480, 0.1096908636190696),
 (4000, 0.1096908636190696),
 (654, 0.10889310129609417),
 (454, 0.10879853497231115),
 (3376, 0.10830607221477648),
 (160, 0.10770505460691618),
 (14, 0.107682623063487),
 (126, 0.107682623063487),
 (166, 0.107682623063487),
 (438, 0.107682623063487),
 (3212, 0.10726454129012915),
 (900, 0.10660035817780522),
 (1617, 0.10660035817780522),
 (2789, 0.10660035817780522),
 (134, 0.10660035817780521),
 (167, 0.10660035817780521),
 (249, 0.10660035817780521),
 (786, 0.10660035817780521),
 (1274, 0.10660035817780521),
 (2148, 0.10660035817780521),
 (1002, 0.10586770098608782),
 (368, 0.10497277621629561),
 (678, 0.10497277621629561),
 (1096, 0.10497277621629561),
 (1833, 0.10497277621629561),
 (4468, 0.10497277621629561),
 (536, 0.10453025125088636),
 (3147, 0.1044465935734187),
 (1497, 0.10444659357341869),
 (2331, 0.1037571695799112),
 (228, 0.10353942082032278),
 (432, 0.10353942082032278),
 (740, 0.10353942082032278),
 (1512, 0.10353942082032278),
 (2284, 0.10353942082032278),
 (3630, 0.10353942082032278),
 (50, 0.10341753799900383),
 (1031, 0.10341753799900383),
 (2817, 0.10341753799900383),
 (467, 0.10257624248277727),
 (870, 0.10257624248277727),
 (87, 0.1019294382875251),
 (422, 0.1019294382875251),
 (483, 0.1019294382875251),
 (238, 0.10176802973291377),
 (420, 0.10163945352271772),
 (85, 0.10154529930749041),
 (2634, 0.10112997936948631),
 (2674, 0.10112997936948631),
 (3721, 0.10112997936948631),
 (43, 0.10072787050317253),
 (123, 0.10072787050317253),
 (2547, 0.10072787050317253),
 (3093, 0.10072787050317253),
 (232, 0.10050378152592121),
 (332, 0.10050378152592121),
 (544, 0.10050378152592121),
 (781, 0.10050378152592121),
 (2060, 0.10050378152592121),
 (2865, 0.10050378152592121),
 (3498, 0.10050378152592121),
 (4097, 0.10050378152592121),
 (4777, 0.10050378152592121),
 (81, 0.09988907373180403),
 (229, 0.09988907373180403),
 (3309, 0.09984038297885897),
 (1574, 0.09928550884822428),
 (889, 0.09927330486454494),
 (148, 0.09913631941932194),
 (236, 0.09913631941932194),
 (2741, 0.09913631941932194),
 (3407, 0.09913631941932194),
 (3428, 0.09913631941932194),
 (3926, 0.09913631941932194),
 (997, 0.09897594780811197),
 (1418, 0.09897594780811197),
 (307, 0.09883693657685838),
 (627, 0.09869275424396534),
 (1348, 0.09869275424396534),
 (2521, 0.09869275424396534),
 (3083, 0.09869275424396534),
 (4203, 0.09869275424396534),
 (199, 0.09813358399735746),
 (270, 0.09813358399735746),
 (2099, 0.09813358399735746),
 (2439, 0.09813358399735746),
 (939, 0.09811049102515929),
 (1616, 0.0978231976089037),
 (2175, 0.0978231976089037),
 (2247, 0.0978231976089037),
 (4019, 0.0978231976089037),
 (2106, 0.09731236802019037),
 (754, 0.09656090991705352),
 (814, 0.09656090991705352),
 (1037, 0.09656090991705352),
 (1237, 0.09656090991705352),
 (2072, 0.09656090991705352),
 (182, 0.09651142956027287),
 (572, 0.09651142956027287),
 (1455, 0.09651142956027287),
 (808, 0.09642365197998373),
 (1156, 0.09642365197998373),
 (1524, 0.09642365197998373),
 (3621, 0.09642365197998373),
 (3663, 0.09642365197998373),
 (4198, 0.09642365197998373),
 (52, 0.09572994763343545),
 (75, 0.09534625892455924),
 (223, 0.09534625892455924),
 (1290, 0.09534625892455924),
 (262, 0.09496714704969828),
 (425, 0.09496714704969828),
 (653, 0.09430419201928972),
 (1501, 0.09430419201928972),
 (2762, 0.09430419201928972),
 (3839, 0.09430419201928972),
 (170, 0.09422229518055114),
 (692, 0.09422229518055114),
 (1405, 0.09422229518055114),
 (1496, 0.09422229518055114),
 (2498, 0.09422229518055114),
 (687, 0.09417632186960223),
 (787, 0.09417632186960223),
 (1614, 0.09417632186960223),
 (3340, 0.09417632186960223),
 (3874, 0.09417632186960223),
 (3441, 0.09349469900084573),
 (28, 0.09304842103984709),
 (203, 0.09304842103984709),
 (449, 0.09304842103984709),
 (1823, 0.09304842103984709),
 (189, 0.09231861823449956),
 (3055, 0.09231861823449956),
 (239, 0.09208868358546966),
 (491, 0.09208868358546966),
 (68, 0.09196009797434057),
 (295, 0.09196009797434057),
 (472, 0.09196009797434057),
 (632, 0.09196009797434057),
 (1097, 0.09196009797434057),
 (1109, 0.09196009797434057),
 (1145, 0.09196009797434057),
 (1158, 0.09196009797434057),
 (1294, 0.09196009797434057),
 (1771, 0.09196009797434057),
 (2253, 0.09196009797434057),
 (2556, 0.09196009797434057),
 (3152, 0.09196009797434057),
 (3620, 0.09196009797434057),
 (3783, 0.09196009797434057),
 (21, 0.09090909090909091),
 (131, 0.09090909090909091),
 (510, 0.09090909090909091),
 (988, 0.09090909090909091),
 (1113, 0.09090909090909091),
 (2787, 0.09045340337332909),
 (4472, 0.09045340337332909),
 (1775, 0.09009374626955591),
 (4545, 0.09009374626955591),
 (10, 0.08989331499509895),
 (480, 0.08989331499509895),
 (2241, 0.08989331499509895),
 (3755, 0.08989331499509895),
 (3935, 0.08989331499509895),
 (5, 0.08945703337056415),
 (213, 0.08945703337056415),
 (312, 0.08891084489487741),
 (535, 0.08891084489487741),
 (643, 0.08891084489487741),
 (1082, 0.08891084489487741),
 (1195, 0.08891084489487741),
 (2592, 0.08891084489487741),
 (2650, 0.08891084489487741),
 (3008, 0.08891084489487741),
 (153, 0.0888336318148377),
 (1575, 0.0886968593983624),
 (2323, 0.0886968593983624),
 (2456, 0.0886968593983624),
 (2645, 0.0886968593983624),
 (3736, 0.0886968593983624),
 (3901, 0.0886968593983624),
 (4018, 0.0886968593983624),
 (4256, 0.0886968593983624),
 (4490, 0.0886968593983624),
 (1439, 0.08822308415507318),
 (266, 0.0879598994267085),
 (371, 0.0879598994267085),
 (3255, 0.0879598994267085),
 (3611, 0.0879598994267085),
 (4180, 0.0879598994267085),
 (18, 0.0876249546540977),
 (363, 0.0876249546540977),
 (121, 0.08703882797784893),
 (193, 0.08703882797784893),
 (410, 0.08703882797784893),
 (660, 0.08703882797784893),
 (1077, 0.08703882797784893),
 (1446, 0.08703882797784893),
 (1686, 0.08703882797784893),
 (1727, 0.08703882797784893),
 (2161, 0.08703882797784893),
 (2820, 0.08703882797784893),
 (3634, 0.08703882797784893),
 (4135, 0.08703882797784893),
 (4205, 0.08703882797784893),
 (4331, 0.08703882797784893),
 (4403, 0.08703882797784893),
 (230, 0.08646430798325933),
 (1692, 0.0861460984507896),
 (2527, 0.0861460984507896),
 (3140, 0.0861460984507896),
 (4343, 0.0861460984507896),
 (256, 0.08547043234472845),
 (624, 0.08547043234472845),
 (715, 0.08547043234472845),
 (791, 0.08547043234472845),
 (1721, 0.08547043234472845),
 (2053, 0.08547043234472845),
 (2396, 0.08547043234472845),
 (3483, 0.08547043234472845),
 (3537, 0.08547043234472845),
 (3954, 0.08547043234472845),
 (1487, 0.08534859274986485),
 (334, 0.08528028654224418),
 (1846, 0.08528028654224418),
 (3389, 0.08528028654224418),
 (3553, 0.08528028654224418),
 (2570, 0.0848066914440948),
 (11, 0.0844400661841498),
 (419, 0.0844400661841498),
 (445, 0.0844400661841498),
 (898, 0.0844400661841498),
 (1906, 0.0844400661841498),
 (785, 0.08427498280790527),
 (799, 0.08427498280790527),
 (200, 0.08398387664337814),
 (794, 0.08398387664337814),
 (1280, 0.08398387664337814),
 (2093, 0.08398387664337814),
 (2562, 0.08398387664337814),
 (2651, 0.08398387664337814),
 (2868, 0.08398387664337814),
 (2957, 0.08398387664337814),
 (3448, 0.08398387664337814),
 (301, 0.08375315127160099),
 (278, 0.08362420100070908),
 (331, 0.08362420100070908),
 (412, 0.08362420100070908),
 (596, 0.08362420100070908),
 (602, 0.08362420100070908),
 (2488, 0.08362420100070908),
 (2713, 0.08362420100070908),
 (3462, 0.08362420100070908),
 (3720, 0.08362420100070908),
 (3881, 0.08362420100070908),
 (4516, 0.08362420100070908),
 (234, 0.08283153665625823),
 (508, 0.08283153665625823),
 (1701, 0.08283153665625823),
 (2115, 0.0827379240401869),
 (319, 0.08257228238447704),
 (1259, 0.08257228238447704),
 (1306, 0.08257228238447704),
 (1480, 0.08257228238447704),
 (2216, 0.08257228238447704),
 (274, 0.08215419219227854),
 (217, 0.08206099398622183),
 (1175, 0.08206099398622183),
 (2035, 0.08206099398622183),
 (479, 0.08175874252096607),
 (827, 0.08131156281817417),
 (1233, 0.08131156281817417),
 (2354, 0.08131156281817417),
 (209, 0.08122955416108235),
 (233, 0.08122955416108235),
 (244, 0.08122955416108235),
 (356, 0.08122955416108235),
 (1745, 0.08122955416108235),
 (2251, 0.08122955416108235),
 (143, 0.08058229640253803),
 (330, 0.08058229640253803),
 (383, 0.08058229640253803),
 (752, 0.08058229640253803),
 (1276, 0.08058229640253803),
 (1357, 0.08058229640253803),
 (2109, 0.08058229640253803),
 (2792, 0.08058229640253803),
 (2796, 0.08058229640253803),
 (3556, 0.08058229640253803),
 (4353, 0.08058229640253803),
 (4502, 0.08058229640253803),
 (3368, 0.08026441628216505),
 (141, 0.0799502686333539),
 (389, 0.0799502686333539),
 (1474, 0.0799502686333539),
 (1854, 0.0799502686333539),
 (3135, 0.0799502686333539),
 (3678, 0.0799502686333539),
 (4754, 0.0799502686333539),
 (243, 0.07987230638308718),
 (671, 0.07987230638308718),
 (746, 0.07987230638308718),
 (1832, 0.07987230638308718),
 (2363, 0.07987230638308718),
 (2740, 0.07987230638308718),
 (3905, 0.07987230638308718),
 (813, 0.07918075824648958),
 (1030, 0.07918075824648958),
 (1634, 0.07901744265512675),
 (745, 0.0787295821622217),
 (1589, 0.0787295821622217),
 (1756, 0.0787295821622217),
 (2644, 0.0787295821622217),
 (2660, 0.0787295821622217),
 (4560, 0.0787295821622217),
 (103, 0.07850686719788597),
 (1639, 0.07850686719788597),
 (129, 0.0778498944161523),
 (473, 0.0778498944161523),
 (541, 0.0778498944161523),
 (1019, 0.0778498944161523),
 (2968, 0.0778498944161523),
 (3728, 0.0778498944161523),
 (4587, 0.0778498944161523),
 (4654, 0.0778498944161523),
 (4737, 0.0778498944161523),
 (263, 0.07756315349925287),
 (292, 0.07756315349925287),
 (511, 0.07756315349925287),
 (564, 0.07756315349925287),
 (960, 0.07756315349925287),
 (980, 0.07756315349925287),
 (1378, 0.07756315349925287),
 (1586, 0.07756315349925287),
 (1928, 0.07756315349925287),
 (3301, 0.07756315349925287),
 (3322, 0.07756315349925287),
 (4657, 0.07756315349925287),
 (3, 0.07733602811121826),
 (2448, 0.07733602811121826),
 (734, 0.07720914364821829),
 (1011, 0.07720914364821829),
 (45, 0.07658395810674837),
 (2386, 0.07653459686532839),
 (2, 0.07644707871564382),
 (775, 0.07644707871564382),
 (863, 0.07644707871564382),
 (878, 0.07644707871564382),
 (922, 0.07644707871564382),
 (1142, 0.07644707871564382),
 (2167, 0.07644707871564382),
 (2400, 0.07644707871564382),
 (2583, 0.07644707871564382),
 (2661, 0.07644707871564382),
 (4626, 0.07644707871564382),
 (63, 0.07597371763975862),
 (169, 0.07597371763975862),
 (768, 0.07597371763975862),
 (4506, 0.07597371763975862),
 (9, 0.07537783614444091),
 (23, 0.07537783614444091),
 (88, 0.07537783614444091),
 (142, 0.07537783614444091),
 (369, 0.07537783614444091),
 (400, 0.07537783614444091),
 (899, 0.07537783614444091),
 (901, 0.07537783614444091),
 (1139, 0.07537783614444091),
 (1249, 0.07537783614444091),
 (1519, 0.07537783614444091),
 (1573, 0.07537783614444091),
 (1747, 0.07537783614444091),
 (1884, 0.07537783614444091),
 (2274, 0.07537783614444091),
 (2304, 0.07537783614444091),
 (2445, 0.07537783614444091),
 (2671, 0.07537783614444091),
 (2715, 0.07537783614444091),
 (2856, 0.07537783614444091),
 (2880, 0.07537783614444091),
 (3102, 0.07537783614444091),
 (3470, 0.07537783614444091),
 (3527, 0.07537783614444091),
 (3560, 0.07537783614444091),
 (3949, 0.07537783614444091),
 (4279, 0.07537783614444091),
 (4316, 0.07537783614444091),
 (4641, 0.07537783614444091),
 (486, 0.07500375028127344),
 (1783, 0.07479575920067658),
 (125, 0.07460470969529907),
 (12, 0.07435223956449145),
 (306, 0.07435223956449145),
 (315, 0.07435223956449145),
 (349, 0.07435223956449145),
 (920, 0.07435223956449145),
 (1166, 0.07435223956449145),
 (1207, 0.07435223956449145),
 (1942, 0.07435223956449145),
 (3028, 0.07435223956449145),
 (3233, 0.07435223956449145),
 (3297, 0.07435223956449145),
 (3764, 0.07435223956449145),
 (3816, 0.07435223956449145),
 (3851, 0.07435223956449145),
 (190, 0.07422696190252054),
 (222, 0.07422696190252054),
 (19, 0.07367094686837573),
 (48, 0.07367094686837573),
 (612, 0.07367094686837573),
 (618, 0.07367094686837573),
 (1346, 0.07367094686837573),
 (1828, 0.07367094686837573),
 (35, 0.07336739820667779),
 (325, 0.07336739820667779),
 (457, 0.07336739820667779),
 (894, 0.07336739820667779),
 (1027, 0.07336739820667779),
 (1749, 0.07336739820667779),
 (2128, 0.07336739820667779),
 (2295, 0.07336739820667779),
 (164, 0.07336739820667777),
 (1924, 0.07312724241271307),
 (3978, 0.07312724241271307),
 (4492, 0.07312724241271307),
 (51, 0.07259540086406277),
 (501, 0.07259540086406277),
 (1898, 0.07259540086406277),
 (33, 0.07242068243779014),
 (1523, 0.07242068243779014),
 (2683, 0.07242068243779014),
 (3805, 0.07242068243779014),
 (812, 0.07207499701564472),
 (1305, 0.07207499701564472),
 (1534, 0.07207499701564471),
 (32, 0.07156562669645132),
 (607, 0.07156562669645132),
 (1926, 0.07156562669645132),
 (2005, 0.07156562669645132),
 (854, 0.07150969419341943),
 (1032, 0.07150969419341943),
 (1161, 0.07150969419341943),
 (1181, 0.07150969419341943),
 (4268, 0.07150969419341943),
 (4558, 0.07150969419341943),
 (4624, 0.07150969419341943),
 (534, 0.07106690545187015),
 (1530, 0.07106690545187015),
 (2712, 0.07106690545187015),
 (2801, 0.07106690545187015),
 (2861, 0.07106690545187015),
 (3180, 0.07106690545187015),
 (3431, 0.07106690545187015),
 (3832, 0.07106690545187015),
 (4011, 0.07106690545187015),
 (4236, 0.07106690545187015),
 (105, 0.07063224140220167),
 (241, 0.07063224140220167),
 (362, 0.07063224140220167),
 (402, 0.07063224140220167),
 (587, 0.07063224140220167),
 (1080, 0.07063224140220167),
 (2018, 0.07063224140220167),
 (2163, 0.07063224140220167),
 (3164, 0.07063224140220167),
 (403, 0.07057846732405855),
 (2203, 0.07057846732405855),
 (3331, 0.07029019463944167),
 (286, 0.07009996372327816),
 (1659, 0.07009996372327816),
 (4429, 0.07009996372327816),
 (37, 0.06978631577988531),
 (227, 0.06978631577988531),
 (235, 0.06978631577988531),
 (242, 0.06978631577988531),
 (492, 0.06978631577988531),
 (547, 0.06978631577988531),
 (855, 0.06978631577988531),
 (1269, 0.06978631577988531),
 (1293, 0.06978631577988531),
 (2851, 0.06978631577988531),
 (2938, 0.06978631577988531),
 (3285, 0.06978631577988531),
 (38, 0.06963106238227913),
 (246, 0.06963106238227913),
 (1282, 0.06963106238227913),
 (381, 0.06917144638660747),
 (1664, 0.06917144638660747),
 (1770, 0.06917144638660747),
 (2165, 0.06917144638660747),
 (2297, 0.06917144638660747),
 (2877, 0.06917144638660747),
 (3117, 0.06917144638660747),
 (4431, 0.06917144638660747),
 (39, 0.06897007348075543),
 (70, 0.06897007348075543),
 (98, 0.06897007348075543),
 (112, 0.06897007348075543),
 (207, 0.06897007348075543),
 (219, 0.06897007348075543),
 (680, 0.06897007348075543),
 (1367, 0.06897007348075543),
 (2235, 0.06897007348075543),
 (2449, 0.06897007348075543),
 (2852, 0.06897007348075543),

In [47]:
def recommend (movie):
    movie_index = new_df[new_df['title']==movie].index[0]
    distance = similarity[movie_index]
    movies_list =sorted(list(enumerate(distance)),reverse=True,key = lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)
        # print(i[0])

In [48]:
recommend('Avatar')

Aliens vs Predator: Requiem
Battle: Los Angeles
Predator
Falcon Rising
Independence Day

In [49]:
recommend('Batman')

Batman
Batman & Robin
Batman Returns
The R.M.
Batman

In [50]:
new_df.iloc[1216].title

'Aliens vs Predator: Requiem'

In [51]:
import pickle

pickle.dump(new_df,open('movies.pkl','wb'))

In [52]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [53]:
pickle.dump(similarity,open('similarity.pkl','wb'))